### ISSUE TITLE
佩服，大三，就这么厉害了

### ISSUE THREAD

**Issue by songxing10000** [skytoup/SkyRadiusView#1]
IBInspectable 这个是什么时候出来的啊，对版本适配有影响吗

**Comment by skytoup** [comment]
只是Xcode6的一个功能

**Comment by songxing10000** [comment]
安装Xcode6.4这么久了， 怎么没看到哪里有介绍啊，你是在哪里看到的啊，我在Xcode文档里也没看到个

在 2015-08-17 13:36:07，"skytoup" notifications@github.com 写道：

只是Xcode6的一个功能

**Comment by skytoup** [comment]
这里有文章，官方更新日志不知道有没有：http://www.cocoachina.com/ios/20150227/11202.html
